### ISSUE TITLE
When enable consolidate-commits, commit message's placeholder not been replaced

### ISSUE THREAD

**Issue by jolestar** [crate-ci/cargo-release#222]
release.toml

```toml
disable-push = true
disable-publish = true
disable-tag = true
consolidate-commits = true
pre-release-commit-message = "Release {{version}}"
post-release-commit-message = "Released {{version}}, starting {{next_version}}"
```
I try to add pre-release-commit-message template config or use the default message template.

commit message:
```
Author: jolestar <jolestar@gmail.com>
Date:   Tue Jul 21 15:41:24 2020 +0800

    Released {{version}}, starting {{next_version}}

commit e7ce20ec0473f75f4275dbd99582494b6f4f2369
Author: jolestar <jolestar@gmail.com>
Date:   Tue Jul 21 15:40:36 2020 +0800

    Release {{version}}

```
