### ISSUE TITLE
Allow using single tag for all crates in workspace

### ISSUE THREAD

**Issue by kelnos** [crate-ci/cargo-release#333]
I noticed `cargo-release` creates a tag for each crate in a multi-crate workspace, with the version prefixed by the name of the crate.  However, I really just want a single tag for the entire release (so instead of `crate1-v0.1.0`, `crate2-v0.1.0`, I just want `v0.1.0`).  I can't seem to figure out how to accomplish this. I tried `--tag-prefix v`, but it tries to tag twice with the same tag name, and fails.

**Comment by epage** [comment]
I would add
```toml
[workspace.metadata.release]
disable-tag = true
```

and then for the one crate that you want the tag associated with
```toml
[package.metadata.release]
disable-tag = false
```

See https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md#config-fields
