### ISSUE TITLE
Impossible to use `^` and `$` anchors in `pre-release-replacements` search regex

### ISSUE THREAD

**Issue by MicroJoe** [crate-ci/cargo-release#412]
When using the “version” string in multiple places in a `Cargo.toml` file:

```toml
[package]
name = "gladis"
version = "1.0.2-alpha.0"

# ...

[dependencies]
gladis_proc_macro = { version = "1.0.2-alpha.0", optional = true, path = "../gladis_proc_macro" }
```

The simple `search="version = .*"` used in `pre-release-replacements` will match *both* the package version and the version of the dependency. Indeed, from the [documentation of the regex crate](https://docs.rs/regex/latest/regex/), the match will not check the newlines by default:

> Notice the use of the ^ and $ anchors. In this crate, every expression is executed with an implicit .*? at the beginning and end, which allows it to match anywhere in the text. Anchors can be used to ensure that the full text matches an expression.

This is problematic, because the replacing template needs to be different depending on the line one wants to modify. It looks like using anchors inside of the regular expressions would be the best option. However, when adding the `^` and `$` anchors in the `search` attribute for a simple `README.md` example, nothing will be matched:
  
`README.md`
    
    ```toml
    [dependencies]
    gladis = "1.0.1"
    ```
    
`release.toml`

    pre-release-replacements = [
      {file="README.md", search="^gladis = .*$", replace="gladis = \"{{version}}\""},
    ]

`cargo release`

    [2022-02-02T14:30:26Z ERROR cargo_release] Fatal: For `^gladis = .*$`, at least 1 replacements expected, found 0

But without the anchors, it works:

```
pre-release-replacements = [
  {file="README.md", search="gladis = .*", replace="gladis = \"{{version}}\""},
]
```

Without the ability to use anchors in regular expressions, it is impossible to properly update a `Cargo.toml` file containing multiple `version` strings both in package info and in its dependencies, like example provided at the top of this issue.
