### ISSUE TITLE
Captures in replacements

### ISSUE THREAD

**Issue by passcod** [crate-ci/cargo-release#418]
I'm converting my custom release scripts to this crate and I have replacements that use regex captures. My specific case is that I have snapshot tests for the help messages, and those include the version. So my custom scripts do this:

```bash
sed -E -i "s/watchexec(.exe)? $extver/watchexec\1 $newver/" cli/tests/snapshots/help__*
```

Disregarding the glob in `cli/tests/snapshots/help__*` (I'll open another request for it), replicating this in release.toml looks a bit like:

```toml
[[pre-release-replacements]]
file = "tests/snapshots/help__help_windows.snap"
search = "watchexec.exe [\\d.]+"
replace = "watchexec.exe {{version}}"
prerelease = true
min = 0
max = 1

[[pre-release-replacements]]
file = "tests/snapshots/help__help_unix.snap"
search = "watchexec [\\d.]+"
replace = "watchexec {{version}}"
prerelease = true
min = 0
max = 1
```

It's annoying to have to repeat this. I'd much rather do:

```toml
[[pre-release-replacements]]
file = "tests/snapshots/help__*.snap"
search = "watchexec(.exe)? [\\d.]+"
replace = "watchexec{{1}} {{version}}"
prerelease = true
max = 1
```

or something like it.
