### ISSUE TITLE
Globs or multiple files in replacements

### ISSUE THREAD

**Issue by passcod** [crate-ci/cargo-release#419]
I'm converting my custom release scripts to this crate and I have replacements that apply to multiple files. My specific case is that I have snapshot tests for the help messages, and those include the version. So my custom scripts do this:

```bash
sed -E -i "s/watchexec(.exe)? $extver/watchexec\1 $newver/" cli/tests/snapshots/help__*
```

Disregarding the capture in the regex (see #418), replicating this in release.toml looks a bit like:

```toml
[[pre-release-replacements]]
file = "tests/snapshots/help__help_windows.snap"
// ...

[[pre-release-replacements]]
file = "tests/snapshots/help__help_unix.snap"
// ...
```

It's annoying to have to repeat this. I'd much rather do:

```toml
[[pre-release-replacements]]
file = "tests/snapshots/help__*.snap"
// ...
```

or maybe

```toml
[[pre-release-replacements]]
file = [
  "tests/snapshots/help__help_unix.snap",
  "tests/snapshots/help__help_windows.snap",
]
// ...
```
