### ISSUE TITLE
Old version for use in search patterns in replacements

### ISSUE THREAD

**Issue by passcod** [crate-ci/cargo-release#420]
I'm converting my custom release scripts to this crate (see #418, #419 also). One thing I do there for guarding against imprecise regex searches is have the search include the old/current version.

E.g. if there's two readme sections like:

```markdown
To install:

`​``
crate-name = "3.0.0-pre.42"
`​``

If you'd like to use the old, stable version, however, use:

`​``
crate-name = "2.1.0"
`​``
```

When releasing, if I do things naïvely, I might have a config like:

```toml
file = "README.md"
search = "^crate-name = \"[\d.]+(-.+)?\""
replace = "crate-name = \"{{version}}\""
```

And when I release, both bleeding edge and "old stable" version instructions will get changed! Oh no.

I can use `max = 1`, but what if I also want to replace another instance which is further away in the file? Or what if I forget and re-order the sections in the readme?

I've run into such situations before, and my solution was to have something like this:

```bash
sed -E -i "s/^version: \"$extver\"/version: \"$newver\"/" filepath
```

`$extver` is the extant version, the one that currently should be there. This makes it much less probable to run into issues with incorrect search matches, though it trades some flexibility (if there's a version drift or mismatch, it can miss replaces).

It's a bit awkward to make substitutions to regexes, so it should probably be opt-in if implemented, e.g.

```toml
file = "README.md"
search-substitutions = true
search = "^crate-name = \"{{old_version}}\""
replace = "crate-name = \"{{version}}\""
```

For a practical example, see [this section in `watchexec/watchexec`](https://github.com/watchexec/watchexec/blob/1e381820ccbfe4adaa21597ef2524b060014f592/cli/release.toml#L25-L30), where the only reason there's two tabs in the search and replace is to differentiate [the correct version field](https://github.com/watchexec/watchexec/blob/bd7a9339060a98d8b2dbe8cd7dbb4ab0abc5b3f4/cli/watchexec.exe.manifest#L6) from a [decidedly incorrect one](https://github.com/watchexec/watchexec/blob/bd7a9339060a98d8b2dbe8cd7dbb4ab0abc5b3f4/cli/watchexec.exe.manifest#L1).
