### ISSUE TITLE
Shared version + pre-version create releases with pre-version dependencies

### ISSUE THREAD

**Issue by plule** [crate-ci/cargo-release#456]
I'd like to use cargo release in a workspace with a shared version, and always have the main branch versionned as `<next version>-alpha.0`. However, on release, the crates get released as `<next version>` but the dependencies are still `<next version>-alpha.0`.

I'm not sure if it's an edge case, or a misconfiguration. Here is a reproduction:

## Setup
`cargo-release 0.20.5`

```sh
cargo new shared-preversion
cd shared-preversion
cargo new inner-dep --lib
```

`shared-preversion/Cargo.toml`
```toml
[package]
name = "shared-preversion"
version = "1.0.0-alpha.0"
edition = "2021"

[dependencies]
inner-dep = { version = "1.0.0-alpha.0", path = "inner-dep"}

[workspace]
members = ["inner-dep"]
```

`shared-preversion/release.toml`
```toml
shared-version = true
dev-version = true
```

`shared-preversion/inner-dep/Cargo.toml`
```toml
[package]
name = "inner-dep"
version = "1.0.0-alpha.0"
edition = "2021"

[dependencies]
```

`shared-preversion/inner-dep/release.toml`

```toml
shared-version = true
```

## Releasing 1.0.0

```sh
cargo release --workspace --execute --no-publish --no-push
```

## Result

As expected, a v1.0.0 tag was created with both crates versioned as 1.0.0. However, in this tag, the declared dependency is:

```toml
[dependencies]
inner-dep = { version = "1.0.0-alpha.0", path = "inner-dep"}
```

## Expected

```toml
[dependencies]
inner-dep = { version = "1.0.0", path = "inner-dep"}
```

## Note

I tried to avoid having the `-alpha.0` suffix in the dependency in the first place, but cargo build would not allow it: `prerelease package needs to be specified explicitly`.
