### ISSUE TITLE
`pre-release-commit-message` does not replace `{{version}}` despite `consolidate-commits = false`

### ISSUE THREAD

**Issue by LeoniePhiline** [crate-ci/cargo-release#680]
I have set `consolidate-commits = false`.

Yet still `cargo release commit -x` created a commit with the following message:

> release: {{version}}

Instead of 

> release: 0.3.0

Am I doing something wrong or might this be a bug?

Config:

```toml
allow-branch = ["main"]
consolidate-commits = false
pre-release-commit-message = "release: {{version}}"
```

Using cargo-release `0.24.10`
