### ISSUE TITLE
`tag-message` in configuration is not respected

### ISSUE THREAD

**Issue by azzamsa** [crate-ci/cargo-release#687]
Hi.

I have set `tag-message` in `Cargo.toml`

```toml
[package.metadata.release]
tag-message = "{{version}}"
```

But, I still get this commit format:

`chore: Release nai version 0.2.1`

![image](https://github.com/crate-ci/cargo-release/assets/17734314/c90dd4b2-d59e-40c1-ad6e-f2506229b9be)

Thanks!
