### ISSUE TITLE
"Failed to parse manifest ... missing field `name` in `package`" with workspace

### ISSUE THREAD

**Issue by 9999years** [crate-ci/cargo-release#703]
With this Cargo workspace `Cargo.toml`:

```toml
[workspace]
members = [
    "ghcid-ng",
    "test-harness",
    "test-harness-macro",
]
resolver = "2"

[package.metadata.release]
pre-release-commit-message = "Release {{crate_name}} version {{version}}"
```

Running `cargo release patch` gives me the following error:

```
$ cargo release patch
error: `cargo metadata` exited with an error: error: failed to parse manifest at `/Users/wiggles/ghcid-ng/Cargo.toml`

Caused by:
  missing field `name`
  in `package`
```

[The docs](https://github.com/crate-ci/cargo-release/blob/f2307121c187cab3ed694c4536d11340904907b8/docs/reference.md) suggest that at least some configuration is allowed in the workspace `Cargo.toml`, and if I remove the offending clause and run `cargo release config`, which the `cargo release` help describes as "Dump workspace configuration", the `pre-release-commit-message` field is shown in the output, suggesting I should be able to have it in my workspace `Cargo.toml`.

Anyways, the intended usage is a bit unclear here. I can work around this by putting my settings in the relevant crate `Cargo.toml`s (my workspace only has one crate I actually want to release), but I'm not sure if I'm holding the tool wrong or what.

Thanks for any help!
