### ISSUE TITLE
release hangs when publishing to private repository

### ISSUE THREAD

**Issue by Xerxes004** [crate-ci/cargo-release#813]
Cargo release version 0.25.10.

I have a private repository in my `config.toml` file called `MyRepo`.

When I release with this command, it hangs indefinitely at `Waiting on my_repo to propagate to index`.

```bash
cargo release patch -x --no-confirm
```

But if I release with this command, it does not hang.

```bash
cargo release patch --registry MyRepo -x --no-confirm
```

My crate's `Cargo.toml` looks like this to prevent publishing to crates.io by accident:

```toml
[package]
name = "my_crate"
version = "0.1.13"
edition = "2021"
publish = ["MyRepo"]
```
