### ISSUE TITLE
Release command fails when dependencies are located in private registries

### ISSUE THREAD

**Issue by Xerxes004** [crate-ci/cargo-release#815]
I am trying to publish my workspace to a private registry called MyReg. The command fails because `cargo-release` searches `crates-io` index for my private dependency. The packaging and release of `package-one` succeeds as expected, but `package-two` does not. Subsequent runs of the command fails because `package-one` was already released with the version `0.1.0`.

I am publishing with this command:

```bash
cargo release 0.1.0 --registry MyReg -x
```

My dependencies look like:

```
my_workspace:
    - Cargo.toml
    - Cargo.lock
    package-one
        - Cargo.toml
        - src/
    package-two
        - Cargo.toml
        - src/
```

My `Cargo.toml` for `package-one` specifies the registry with:

```toml
# package-one Cargo.toml
# Shortened for readability
[package]
publish = ["MyReg"]
```

My `Cargo.toml` for `package-two` specifies the dependencies with:

```toml
# package-two Cargo.toml
# Shortened for readability
[package]
publish = ["MyReg"]

[dependencies]
package-one = { path = "../package-one", version = "0.1" }
```

The error looks like:

```
... snip ...
 Publishing package-two
    Updating `MyReg` index
   Packaging package-two v0.1.0 (C:\Users\Xerxes004\Code\my_workspace\package-two)
    Packaged 25 files, 105.5KiB (17.4KiB compressed)
   Verifying package-two v0.1.0 (C:\Users\Xerxes004\Code\my_workspace\package-two)
    Updating crates.io index
error: no matching package named `package-one` found
location searched: registry `crates-io`
required by package `package-two v0.1.0 (C:\Users\Xerxes004\Code\my_workspace\package-two)`
```

**Comment by Xerxes004** [comment]
I solved it.

I had to specify `registry` for my dependencies.

Before:

```toml
# package-two Cargo.toml
# Shortened for readability
[package]
publish = ["MyReg"]

[dependencies]
package-one = { path = "../package-one", version = "0.1" }
```

After:
```toml
# package-two Cargo.toml
# Shortened for readability
[package]
publish = ["MyReg"]

[dependencies]
package-one = { path = "../package-one", version = "0.1", registry = "MyReg" }
```
