### ISSUE TITLE
`verify = true` does not seem to work when cross compiling

### ISSUE THREAD

**Issue by baxterjo** [crate-ci/cargo-release#819]
I have a repo that is a workspace, the workspace cargo-release config looks like
```toml
# Cargo.toml
[workspace.metadata.release]
verify = true
target = "aarch64-unknown-linux-gnu" # <- Not my native arch
shared-version = true
```
and the individual package configs look like
```toml
# package/Cargo.toml
[package.metadata.release]
verify = true
target = "aarch64-unknown-linux-gnu" # <- Not my native arch
shared-version = true
```

but when I run `cargo-release`, no verification takes place.

My native arch is `aarch64-apple-darwin`
