### ISSUE TITLE
pre-version-replacements options

### ISSUE THREAD

**Issue by smmoosavi** [crate-ci/cargo-release#830]
The `pre-release-replacements` don't occur during pre-release tags (e.g., 1.0.0-rc.1)

In some cases, replacement should happen during the pre-release tag, such as replacing the version in the `package.json` file:

## Current config

```toml
pre-release-replacements = [
  { file = "../CHANGELOG.md", search = "Unreleased", replace = "{{version}}" },
  { file = "../web/package.json", search = "\"version\": \".*\"", replace = "\"version\": \"{{version}}\"", exactly = 1 },
]
```

## Wanted config

```toml
# run when the release command is executed
pre-release-replacements = [
  { file = "../CHANGELOG.md", search = "Unreleased", replace = "{{version}}" },
]
# run every time version is changed
pre-version-replacements = [
  { file = "../web/package.json", search = "\"version\": \".*\"", replace = "\"version\": \"{{version}}\"", exactly = 1 },
]
```
# Question

What is the best practice for keeping the package.json version in sync?
