### ISSUE TITLE
`--manifest-path` is ignored

### ISSUE THREAD

**Issue by xxshady** [crate-ci/cargo-release#842]
I have the following structure:
```
workspace/
├─ Cargo.toml
├─ crate/
│  ├─ Cargo.toml
```
There is `[workspace.metadata.release]` in workspace/Cargo.toml and `[package.metadata.release]` in workspace/crate/Cargo.toml

when I run `cargo release x.x.x --manifest-path Cargo.toml --execute` in workspace/crate directory `cargo-release` uses `pre-release-commit-message` from workspace/Cargo.toml, and pushed commit message looks like "release new version: {{version}}" (`{{version}}` should be replaced but it's not)

**Comment by xxshady** [comment]
> cargo-release uses pre-release-commit-message from workspace/Cargo.toml

is it expected behavior?

**Comment by epage** [comment]
Do you have a reproduction case I can look at or at least post your full `[*.metadata.release]` config tables?

**Comment by xxshady** [comment]
yea, here it is

```toml
[workspace.metadata.release]
pre-release-commit-message = "release new version: {{version}}"
tag = false
```
```toml
[package.metadata.release]
pre-release-commit-message = "release new version: {{version}} 2"
tag = false
```
