### ISSUE TITLE
Support overriding `pre-release-hook` to empty for workspace packages

### ISSUE THREAD

**Issue by AzurIce** [crate-ci/cargo-release#871]
> I have a set of workspace crates that I am always releasing together, and a single changelog in the workspace root. When running `git cliff` I only want to run it once from the workspace root to update that changelog. But the current pre-release-hook will execute it inside the the crate folders.

I've also encontered this problem from https://github.com/crate-ci/cargo-release/issues/231#issuecomment-1802338188.

In my use case, I have a workspace with root package `ranim` and a member `ranim-macros`, and I want them share the version field from `[workspace.package]`:

```toml
# Cargo.toml
[package]
name = "ranim"
version.workspace = true

[workspace]
members = "packages/*"

[workspace.package]
version = "0.0.0"

[workspace.dependencies]
ranim-macros = { path = "packages/ranim-macros", version = "0.0.0" }
#...

```

```toml
# packages/ranim-macros/Cargo.toml
[package]
name = "ranim-macros"
version.workspace = true
```

Since `ranim` and `ranim-macros` are tightly bounded, I only want one `CHANGELOG.md` for both of them at workspace level.

Now, my settings are like:

```toml
# release.toml
pre-release-hook = ["git", "cliff", "-o", "CHANGELOG.md", "--tag", "{{version}}" ]
```

```toml
# packages/ranim-macros/release.toml

tag = false
# I use this to fix pre-release-hook call on ranim-macros:
# ERROR git_cliff > Git error: `could not find repository at 'H:\_ranim\ranim\packages\ranim-macros'; class=Repository (6); code=NotFound (-3)`
pre-release-hook = ["git", "cliff", "--workdir", "../../", "-o", "../../CHANGELOG.md", "--tag", "{{version}}" ]
```

Although this works, but I thinks it works in a hacky way, the CHANGELOG.md generate twice.

Is there a way of overriding the `pre-release-hook` to empty for child packages?
Maybe something like `pre-release-hook = []` should be expected to work? (however it panics, maybe we should skip the hook step at [src/steps/hook.rs#L193-L198](https://github.com/crate-ci/cargo-release/blob/f7c2975325afc6d6fc1793544802a5578d9ef256/src/steps/hook.rs#L193-L198) if the hook is empty? )
